// PM2 Ecosystem Configuration
// Auto-generated by Wingman - do not edit manually
module.exports = {
  "apps": [
    {
      "name": "honest-ivory-thicket-app-flux-do",
      "namespace": "wingman-apps",
      "script": "bash",
      "args": [
        "-c",
        "PORT=41001 bunx vite"
      ],
      "cwd": "/Users/mini/code/superbased/todo-flux",
      "env": {
        "APP_ID": "ac7df78c-bdb5-40a2-8224-c7931f2993b4",
        "APP_LABEL": "Flux Do",
        "USER_ALIAS": "honest-ivory-thicket",
        "PORT": "41001"
      },
      "out_file": "/Users/mini/code/superbased/todo-flux/apps/logs/honest-ivory-thicket-app-flux-do-out.log",
      "error_file": "/Users/mini/code/superbased/todo-flux/apps/logs/honest-ivory-thicket-app-flux-do-error.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "merge_logs": true,
      "autorestart": false,
      "max_restarts": 0,
      "min_uptime": "5s"
    }
  ]
};
